// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: user_msg.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sex int32

const (
	Sex_BOY  Sex = 0
	Sex_GIRL Sex = 1
)

// Enum value maps for Sex.
var (
	Sex_name = map[int32]string{
		0: "BOY",
		1: "GIRL",
	}
	Sex_value = map[string]int32{
		"BOY":  0,
		"GIRL": 1,
	}
)

func (x Sex) Enum() *Sex {
	p := new(Sex)
	*p = x
	return p
}

func (x Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[0].Descriptor()
}

func (Sex) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[0]
}

func (x Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sex.Descriptor instead.
func (Sex) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{0}
}

type UserStatus int32

const (
	UserStatus_ACTIVE UserStatus = 0
	UserStatus_DELETE UserStatus = 1
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "ACTIVE",
		1: "DELETE",
	}
	UserStatus_value = map[string]int32{
		"ACTIVE": 0,
		"DELETE": 1,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[1].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[1]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{1}
}

type Logic int32

const (
	Logic_LESS       Logic = 0
	Logic_LESS_THAN  Logic = 1
	Logic_EQUAL      Logic = 2
	Logic_GREAT_THAN Logic = 3
	Logic_GREAT      Logic = 4
	Logic_IN         Logic = 5
	Logic_NOT_IN     Logic = 6
	Logic_GROUP_BY   Logic = 7
	Logic_ORDER_BY   Logic = 8
	Logic_NOT_EQUAL  Logic = 9
)

// Enum value maps for Logic.
var (
	Logic_name = map[int32]string{
		0: "LESS",
		1: "LESS_THAN",
		2: "EQUAL",
		3: "GREAT_THAN",
		4: "GREAT",
		5: "IN",
		6: "NOT_IN",
		7: "GROUP_BY",
		8: "ORDER_BY",
		9: "NOT_EQUAL",
	}
	Logic_value = map[string]int32{
		"LESS":       0,
		"LESS_THAN":  1,
		"EQUAL":      2,
		"GREAT_THAN": 3,
		"GREAT":      4,
		"IN":         5,
		"NOT_IN":     6,
		"GROUP_BY":   7,
		"ORDER_BY":   8,
		"NOT_EQUAL":  9,
	}
)

func (x Logic) Enum() *Logic {
	p := new(Logic)
	*p = x
	return p
}

func (x Logic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Logic) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[2].Descriptor()
}

func (Logic) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[2]
}

func (x Logic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Logic.Descriptor instead.
func (Logic) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{2}
}

type UserItem int32

const (
	UserItem_ALL         UserItem = 0
	UserItem_USER_ID     UserItem = 1
	UserItem_USERNAME    UserItem = 2
	UserItem_PASSWORD    UserItem = 4
	UserItem_TELEPHONE   UserItem = 8
	UserItem_SALT        UserItem = 16
	UserItem_NICKNAME    UserItem = 32
	UserItem_SEX         UserItem = 64
	UserItem_BORN_DATE   UserItem = 128
	UserItem_ICON        UserItem = 256
	UserItem_STATUS      UserItem = 512
	UserItem_CREATE_TIME UserItem = 1024
	UserItem_UPDATE_TIME UserItem = 2048
	UserItem_CARD_TYPE   UserItem = 4096
	UserItem_CARD        UserItem = 8192
)

// Enum value maps for UserItem.
var (
	UserItem_name = map[int32]string{
		0:    "ALL",
		1:    "USER_ID",
		2:    "USERNAME",
		4:    "PASSWORD",
		8:    "TELEPHONE",
		16:   "SALT",
		32:   "NICKNAME",
		64:   "SEX",
		128:  "BORN_DATE",
		256:  "ICON",
		512:  "STATUS",
		1024: "CREATE_TIME",
		2048: "UPDATE_TIME",
		4096: "CARD_TYPE",
		8192: "CARD",
	}
	UserItem_value = map[string]int32{
		"ALL":         0,
		"USER_ID":     1,
		"USERNAME":    2,
		"PASSWORD":    4,
		"TELEPHONE":   8,
		"SALT":        16,
		"NICKNAME":    32,
		"SEX":         64,
		"BORN_DATE":   128,
		"ICON":        256,
		"STATUS":      512,
		"CREATE_TIME": 1024,
		"UPDATE_TIME": 2048,
		"CARD_TYPE":   4096,
		"CARD":        8192,
	}
)

func (x UserItem) Enum() *UserItem {
	p := new(UserItem)
	*p = x
	return p
}

func (x UserItem) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserItem) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[3].Descriptor()
}

func (UserItem) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[3]
}

func (x UserItem) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserItem.Descriptor instead.
func (UserItem) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{3}
}

type CardType int32

const (
	CardType_ID_CARD      CardType = 0
	CardType_OFFICER_CARD CardType = 1
)

// Enum value maps for CardType.
var (
	CardType_name = map[int32]string{
		0: "ID_CARD",
		1: "OFFICER_CARD",
	}
	CardType_value = map[string]int32{
		"ID_CARD":      0,
		"OFFICER_CARD": 1,
	}
)

func (x CardType) Enum() *CardType {
	p := new(CardType)
	*p = x
	return p
}

func (x CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[4].Descriptor()
}

func (CardType) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[4]
}

func (x CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardType.Descriptor instead.
func (CardType) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{4}
}

type ConditionValueType int32

const (
	ConditionValueType_NULL         ConditionValueType = 0
	ConditionValueType_INT          ConditionValueType = 1
	ConditionValueType_STRING       ConditionValueType = 2
	ConditionValueType_INT_ARRAY    ConditionValueType = 3
	ConditionValueType_STRING_ARRAY ConditionValueType = 4
)

// Enum value maps for ConditionValueType.
var (
	ConditionValueType_name = map[int32]string{
		0: "NULL",
		1: "INT",
		2: "STRING",
		3: "INT_ARRAY",
		4: "STRING_ARRAY",
	}
	ConditionValueType_value = map[string]int32{
		"NULL":         0,
		"INT":          1,
		"STRING":       2,
		"INT_ARRAY":    3,
		"STRING_ARRAY": 4,
	}
)

func (x ConditionValueType) Enum() *ConditionValueType {
	p := new(ConditionValueType)
	*p = x
	return p
}

func (x ConditionValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_msg_proto_enumTypes[5].Descriptor()
}

func (ConditionValueType) Type() protoreflect.EnumType {
	return &file_user_msg_proto_enumTypes[5]
}

func (x ConditionValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionValueType.Descriptor instead.
func (ConditionValueType) EnumDescriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{5}
}

type UserInfoDB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password   string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Telephone  string `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Salt       string `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	Nickname   string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex        int32  `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	BornDate   uint32 `protobuf:"varint,8,opt,name=born_date,json=bornDate,proto3" json:"born_date,omitempty"`
	Icon       string `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty"`
	CardType   int32  `protobuf:"varint,10,opt,name=card_type,json=cardType,proto3" json:"card_type,omitempty"`
	Card       string `protobuf:"bytes,11,opt,name=card,proto3" json:"card,omitempty"`
	Status     int32  `protobuf:"varint,30,opt,name=status,proto3" json:"status,omitempty"`
	CreateTime string `protobuf:"bytes,31,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime string `protobuf:"bytes,32,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *UserInfoDB) Reset() {
	*x = UserInfoDB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfoDB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoDB) ProtoMessage() {}

func (x *UserInfoDB) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoDB.ProtoReflect.Descriptor instead.
func (*UserInfoDB) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfoDB) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfoDB) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfoDB) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserInfoDB) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *UserInfoDB) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *UserInfoDB) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfoDB) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfoDB) GetBornDate() uint32 {
	if x != nil {
		return x.BornDate
	}
	return 0
}

func (x *UserInfoDB) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UserInfoDB) GetCardType() int32 {
	if x != nil {
		return x.CardType
	}
	return 0
}

func (x *UserInfoDB) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *UserInfoDB) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfoDB) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *UserInfoDB) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type ConditionItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     UserItem           `protobuf:"varint,1,opt,name=key,proto3,enum=UserItem" json:"key,omitempty"`
	Logic   Logic              `protobuf:"varint,2,opt,name=logic,proto3,enum=Logic" json:"logic,omitempty"`
	Vtype   ConditionValueType `protobuf:"varint,3,opt,name=vtype,proto3,enum=ConditionValueType" json:"vtype,omitempty"`
	Ivalue  int64              `protobuf:"varint,10,opt,name=ivalue,proto3" json:"ivalue,omitempty"`
	Svalue  string             `protobuf:"bytes,11,opt,name=svalue,proto3" json:"svalue,omitempty"`
	Iavalue []int64            `protobuf:"varint,12,rep,packed,name=iavalue,proto3" json:"iavalue,omitempty"`
	Savalue []string           `protobuf:"bytes,13,rep,name=savalue,proto3" json:"savalue,omitempty"`
}

func (x *ConditionItem) Reset() {
	*x = ConditionItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionItem) ProtoMessage() {}

func (x *ConditionItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionItem.ProtoReflect.Descriptor instead.
func (*ConditionItem) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ConditionItem) GetKey() UserItem {
	if x != nil {
		return x.Key
	}
	return UserItem_ALL
}

func (x *ConditionItem) GetLogic() Logic {
	if x != nil {
		return x.Logic
	}
	return Logic_LESS
}

func (x *ConditionItem) GetVtype() ConditionValueType {
	if x != nil {
		return x.Vtype
	}
	return ConditionValueType_NULL
}

func (x *ConditionItem) GetIvalue() int64 {
	if x != nil {
		return x.Ivalue
	}
	return 0
}

func (x *ConditionItem) GetSvalue() string {
	if x != nil {
		return x.Svalue
	}
	return ""
}

func (x *ConditionItem) GetIavalue() []int64 {
	if x != nil {
		return x.Iavalue
	}
	return nil
}

func (x *ConditionItem) GetSavalue() []string {
	if x != nil {
		return x.Savalue
	}
	return nil
}

type ConditionItemArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ConditionItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ConditionItemArray) Reset() {
	*x = ConditionItemArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionItemArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionItemArray) ProtoMessage() {}

func (x *ConditionItemArray) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionItemArray.ProtoReflect.Descriptor instead.
func (*ConditionItemArray) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionItemArray) GetItems() []*ConditionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type Condition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	And      *ConditionItemArray   `protobuf:"bytes,1,opt,name=and,proto3" json:"and,omitempty"`
	Or       []*ConditionItemArray `protobuf:"bytes,2,rep,name=or,proto3" json:"or,omitempty"`
	Orderby  *ConditionItem        `protobuf:"bytes,3,opt,name=orderby,proto3" json:"orderby,omitempty"`
	Groupby  *ConditionItem        `protobuf:"bytes,4,opt,name=groupby,proto3" json:"groupby,omitempty"`
	Pagesize int32                 `protobuf:"varint,5,opt,name=pagesize,proto3" json:"pagesize,omitempty"`
	Pagenum  int32                 `protobuf:"varint,6,opt,name=pagenum,proto3" json:"pagenum,omitempty"`
}

func (x *Condition) Reset() {
	*x = Condition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Condition) GetAnd() *ConditionItemArray {
	if x != nil {
		return x.And
	}
	return nil
}

func (x *Condition) GetOr() []*ConditionItemArray {
	if x != nil {
		return x.Or
	}
	return nil
}

func (x *Condition) GetOrderby() *ConditionItem {
	if x != nil {
		return x.Orderby
	}
	return nil
}

func (x *Condition) GetGroupby() *ConditionItem {
	if x != nil {
		return x.Groupby
	}
	return nil
}

func (x *Condition) GetPagesize() int32 {
	if x != nil {
		return x.Pagesize
	}
	return 0
}

func (x *Condition) GetPagenum() int32 {
	if x != nil {
		return x.Pagenum
	}
	return 0
}

type UserInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count     int64         `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Userinfos []*UserInfoDB `protobuf:"bytes,2,rep,name=userinfos,proto3" json:"userinfos,omitempty"`
}

func (x *UserInfos) Reset() {
	*x = UserInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfos) ProtoMessage() {}

func (x *UserInfos) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfos.ProtoReflect.Descriptor instead.
func (*UserInfos) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfos) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *UserInfos) GetUserinfos() []*UserInfoDB {
	if x != nil {
		return x.Userinfos
	}
	return nil
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserItems int64      `protobuf:"varint,1,opt,name=user_items,json=userItems,proto3" json:"user_items,omitempty"`
	Cond      *Condition `protobuf:"bytes,2,opt,name=cond,proto3" json:"cond,omitempty"`
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoReq) GetUserItems() int64 {
	if x != nil {
		return x.UserItems
	}
	return 0
}

func (x *GetUserInfoReq) GetCond() *Condition {
	if x != nil {
		return x.Cond
	}
	return nil
}

type GetUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *UserInfos `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserInfoRes) Reset() {
	*x = GetUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRes) ProtoMessage() {}

func (x *GetUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRes.ProtoReflect.Descriptor instead.
func (*GetUserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserInfoRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserInfoRes) GetData() *UserInfos {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cond *Condition `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
}

func (x *DeleteUserInfoReq) Reset() {
	*x = DeleteUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInfoReq) ProtoMessage() {}

func (x *DeleteUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInfoReq.ProtoReflect.Descriptor instead.
func (*DeleteUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserInfoReq) GetCond() *Condition {
	if x != nil {
		return x.Cond
	}
	return nil
}

type DeleteUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *DeleteUserInfoRes) Reset() {
	*x = DeleteUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserInfoRes) ProtoMessage() {}

func (x *DeleteUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserInfoRes.ProtoReflect.Descriptor instead.
func (*DeleteUserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserInfoRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteUserInfoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CreateUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username  string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password  string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Telephone string   `protobuf:"bytes,3,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Salt      string   `protobuf:"bytes,4,opt,name=salt,proto3" json:"salt,omitempty"`
	Nickname  string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex       Sex      `protobuf:"varint,6,opt,name=sex,proto3,enum=Sex" json:"sex,omitempty"`
	BornDate  uint32   `protobuf:"varint,7,opt,name=born_date,json=bornDate,proto3" json:"born_date,omitempty"`
	Icon      string   `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	CardType  CardType `protobuf:"varint,9,opt,name=card_type,json=cardType,proto3,enum=CardType" json:"card_type,omitempty"`
	Card      string   `protobuf:"bytes,10,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *CreateUserInfoReq) Reset() {
	*x = CreateUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInfoReq) ProtoMessage() {}

func (x *CreateUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInfoReq.ProtoReflect.Descriptor instead.
func (*CreateUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{9}
}

func (x *CreateUserInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserInfoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserInfoReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *CreateUserInfoReq) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *CreateUserInfoReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserInfoReq) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_BOY
}

func (x *CreateUserInfoReq) GetBornDate() uint32 {
	if x != nil {
		return x.BornDate
	}
	return 0
}

func (x *CreateUserInfoReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CreateUserInfoReq) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_ID_CARD
}

func (x *CreateUserInfoReq) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

type CreateUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *UserInfoDB `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CreateUserInfoRes) Reset() {
	*x = CreateUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserInfoRes) ProtoMessage() {}

func (x *CreateUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserInfoRes.ProtoReflect.Descriptor instead.
func (*CreateUserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{10}
}

func (x *CreateUserInfoRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateUserInfoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateUserInfoRes) GetData() *UserInfoDB {
	if x != nil {
		return x.Data
	}
	return nil
}

type ModifyUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cond        *Condition `protobuf:"bytes,1,opt,name=cond,proto3" json:"cond,omitempty"`
	Username    string     `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password    string     `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Telephone   string     `protobuf:"bytes,5,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Salt        string     `protobuf:"bytes,6,opt,name=salt,proto3" json:"salt,omitempty"`
	Nickname    string     `protobuf:"bytes,7,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Sex         Sex        `protobuf:"varint,8,opt,name=sex,proto3,enum=Sex" json:"sex,omitempty"`
	BornDate    uint32     `protobuf:"varint,9,opt,name=born_date,json=bornDate,proto3" json:"born_date,omitempty"`
	Icon        string     `protobuf:"bytes,10,opt,name=icon,proto3" json:"icon,omitempty"`
	CardType    CardType   `protobuf:"varint,11,opt,name=card_type,json=cardType,proto3,enum=CardType" json:"card_type,omitempty"`
	Card        string     `protobuf:"bytes,12,opt,name=card,proto3" json:"card,omitempty"`
	Status      UserStatus `protobuf:"varint,13,opt,name=status,proto3,enum=UserStatus" json:"status,omitempty"`
	ModifyItems int64      `protobuf:"varint,30,opt,name=modify_items,json=modifyItems,proto3" json:"modify_items,omitempty"`
}

func (x *ModifyUserInfoReq) Reset() {
	*x = ModifyUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoReq) ProtoMessage() {}

func (x *ModifyUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoReq.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{11}
}

func (x *ModifyUserInfoReq) GetCond() *Condition {
	if x != nil {
		return x.Cond
	}
	return nil
}

func (x *ModifyUserInfoReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ModifyUserInfoReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ModifyUserInfoReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *ModifyUserInfoReq) GetSalt() string {
	if x != nil {
		return x.Salt
	}
	return ""
}

func (x *ModifyUserInfoReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ModifyUserInfoReq) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_BOY
}

func (x *ModifyUserInfoReq) GetBornDate() uint32 {
	if x != nil {
		return x.BornDate
	}
	return 0
}

func (x *ModifyUserInfoReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ModifyUserInfoReq) GetCardType() CardType {
	if x != nil {
		return x.CardType
	}
	return CardType_ID_CARD
}

func (x *ModifyUserInfoReq) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *ModifyUserInfoReq) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_ACTIVE
}

func (x *ModifyUserInfoReq) GetModifyItems() int64 {
	if x != nil {
		return x.ModifyItems
	}
	return 0
}

type ModifyUserInfoRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *UserInfoDB `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ModifyUserInfoRes) Reset() {
	*x = ModifyUserInfoRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyUserInfoRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyUserInfoRes) ProtoMessage() {}

func (x *ModifyUserInfoRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyUserInfoRes.ProtoReflect.Descriptor instead.
func (*ModifyUserInfoRes) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{12}
}

func (x *ModifyUserInfoRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ModifyUserInfoRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ModifyUserInfoRes) GetData() *UserInfoDB {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetUserInfoByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserItems int64  `protobuf:"varint,1,opt,name=user_items,json=userItems,proto3" json:"user_items,omitempty"`
	UserId    int64  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username  string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Telephone string `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	Card      string `protobuf:"bytes,5,opt,name=card,proto3" json:"card,omitempty"`
}

func (x *GetUserInfoByIDReq) Reset() {
	*x = GetUserInfoByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByIDReq) ProtoMessage() {}

func (x *GetUserInfoByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByIDReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoByIDReq) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserInfoByIDReq) GetUserItems() int64 {
	if x != nil {
		return x.UserItems
	}
	return 0
}

func (x *GetUserInfoByIDReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoByIDReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoByIDReq) GetTelephone() string {
	if x != nil {
		return x.Telephone
	}
	return ""
}

func (x *GetUserInfoByIDReq) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

type GetUserInfoByIDRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *UserInfoDB `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserInfoByIDRes) Reset() {
	*x = GetUserInfoByIDRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_msg_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoByIDRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByIDRes) ProtoMessage() {}

func (x *GetUserInfoByIDRes) ProtoReflect() protoreflect.Message {
	mi := &file_user_msg_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByIDRes.ProtoReflect.Descriptor instead.
func (*GetUserInfoByIDRes) Descriptor() ([]byte, []int) {
	return file_user_msg_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInfoByIDRes) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoByIDRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserInfoByIDRes) GetData() *UserInfoDB {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_user_msg_proto protoreflect.FileDescriptor

var file_user_msg_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xf9, 0x02, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x42, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61,
	0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x1e, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x1f, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x20, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd9, 0x01, 0x0a,
	0x0d, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1b,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x05, 0x6c,
	0x6f, 0x67, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x06, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x63, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x76,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x69, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x61, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x69, 0x61, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x61, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x61, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3a, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x24,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x03, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x52, 0x03, 0x61, 0x6e, 0x64, 0x12, 0x23, 0x0a, 0x02, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x41, 0x72, 0x72, 0x61, 0x79, 0x52, 0x02, 0x6f, 0x72, 0x12, 0x28,
	0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x79, 0x12, 0x28, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x62, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x6e, 0x75, 0x6d, 0x22, 0x4c, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x09, 0x75,
	0x73, 0x65, 0x72, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x42, 0x52, 0x09, 0x75, 0x73, 0x65,
	0x72, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x4f, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x22, 0x56, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x1e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x33, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x39, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x9e, 0x02, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x61, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x73,
	0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03,
	0x73, 0x65, 0x78, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x61, 0x72, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64,
	0x22, 0x5a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x44, 0x42, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x86, 0x03, 0x0a,
	0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x63, 0x6f,
	0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65,
	0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x61, 0x6c, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x61, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x04, 0x2e, 0x53, 0x65, 0x78, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x72, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x6f, 0x72, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f,
	0x6e, 0x12, 0x26, 0x0a, 0x09, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x63, 0x61, 0x72, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61, 0x72,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x23, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x18, 0x1e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x5a, 0x0a, 0x11, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x42, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0x9a, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x74, 0x65, 0x6c, 0x65, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x22, 0x5b,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x44, 0x42, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x18, 0x0a, 0x03, 0x53,
	0x65, 0x78, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x4f, 0x59, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x49, 0x52, 0x4c, 0x10, 0x01, 0x2a, 0x24, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12,
	0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x2a, 0x85, 0x01, 0x0a, 0x05,
	0x4c, 0x6f, 0x67, 0x69, 0x63, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12,
	0x0d, 0x0a, 0x09, 0x4c, 0x45, 0x53, 0x53, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x51, 0x55, 0x41, 0x4c, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x52, 0x45,
	0x41, 0x54, 0x5f, 0x54, 0x48, 0x41, 0x4e, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x45,
	0x41, 0x54, 0x10, 0x04, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x4e, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06,
	0x4e, 0x4f, 0x54, 0x5f, 0x49, 0x4e, 0x10, 0x06, 0x12, 0x0c, 0x0a, 0x08, 0x47, 0x52, 0x4f, 0x55,
	0x50, 0x5f, 0x42, 0x59, 0x10, 0x07, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f,
	0x42, 0x59, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x41,
	0x4c, 0x10, 0x09, 0x2a, 0xd3, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x49, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x55, 0x53, 0x45, 0x52, 0x4e, 0x41,
	0x4d, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44,
	0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x4c, 0x45, 0x50, 0x48, 0x4f, 0x4e, 0x45, 0x10,
	0x08, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x41, 0x4c, 0x54, 0x10, 0x10, 0x12, 0x0c, 0x0a, 0x08, 0x4e,
	0x49, 0x43, 0x4b, 0x4e, 0x41, 0x4d, 0x45, 0x10, 0x20, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x45, 0x58,
	0x10, 0x40, 0x12, 0x0e, 0x0a, 0x09, 0x42, 0x4f, 0x52, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x45, 0x10,
	0x80, 0x01, 0x12, 0x09, 0x0a, 0x04, 0x49, 0x43, 0x4f, 0x4e, 0x10, 0x80, 0x02, 0x12, 0x0b, 0x0a,
	0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x80, 0x04, 0x12, 0x10, 0x0a, 0x0b, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x80, 0x08, 0x12, 0x10, 0x0a, 0x0b,
	0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x80, 0x10, 0x12, 0x0e,
	0x0a, 0x09, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x80, 0x20, 0x12, 0x09,
	0x0a, 0x04, 0x43, 0x41, 0x52, 0x44, 0x10, 0x80, 0x40, 0x2a, 0x29, 0x0a, 0x08, 0x43, 0x61, 0x72,
	0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x44, 0x5f, 0x43, 0x41, 0x52, 0x44,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x46, 0x46, 0x49, 0x43, 0x45, 0x52, 0x5f, 0x43, 0x41,
	0x52, 0x44, 0x10, 0x01, 0x2a, 0x54, 0x0a, 0x12, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x55,
	0x4c, 0x4c, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x49, 0x4e, 0x54,
	0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x52, 0x49,
	0x4e, 0x47, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x10, 0x04, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_msg_proto_rawDescOnce sync.Once
	file_user_msg_proto_rawDescData = file_user_msg_proto_rawDesc
)

func file_user_msg_proto_rawDescGZIP() []byte {
	file_user_msg_proto_rawDescOnce.Do(func() {
		file_user_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_msg_proto_rawDescData)
	})
	return file_user_msg_proto_rawDescData
}

var file_user_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_user_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_msg_proto_goTypes = []interface{}{
	(Sex)(0),                   // 0: Sex
	(UserStatus)(0),            // 1: UserStatus
	(Logic)(0),                 // 2: Logic
	(UserItem)(0),              // 3: UserItem
	(CardType)(0),              // 4: CardType
	(ConditionValueType)(0),    // 5: ConditionValueType
	(*UserInfoDB)(nil),         // 6: UserInfoDB
	(*ConditionItem)(nil),      // 7: ConditionItem
	(*ConditionItemArray)(nil), // 8: ConditionItemArray
	(*Condition)(nil),          // 9: Condition
	(*UserInfos)(nil),          // 10: UserInfos
	(*GetUserInfoReq)(nil),     // 11: GetUserInfoReq
	(*GetUserInfoRes)(nil),     // 12: GetUserInfoRes
	(*DeleteUserInfoReq)(nil),  // 13: DeleteUserInfoReq
	(*DeleteUserInfoRes)(nil),  // 14: DeleteUserInfoRes
	(*CreateUserInfoReq)(nil),  // 15: CreateUserInfoReq
	(*CreateUserInfoRes)(nil),  // 16: CreateUserInfoRes
	(*ModifyUserInfoReq)(nil),  // 17: ModifyUserInfoReq
	(*ModifyUserInfoRes)(nil),  // 18: ModifyUserInfoRes
	(*GetUserInfoByIDReq)(nil), // 19: GetUserInfoByIDReq
	(*GetUserInfoByIDRes)(nil), // 20: GetUserInfoByIDRes
}
var file_user_msg_proto_depIdxs = []int32{
	3,  // 0: ConditionItem.key:type_name -> UserItem
	2,  // 1: ConditionItem.logic:type_name -> Logic
	5,  // 2: ConditionItem.vtype:type_name -> ConditionValueType
	7,  // 3: ConditionItemArray.items:type_name -> ConditionItem
	8,  // 4: Condition.and:type_name -> ConditionItemArray
	8,  // 5: Condition.or:type_name -> ConditionItemArray
	7,  // 6: Condition.orderby:type_name -> ConditionItem
	7,  // 7: Condition.groupby:type_name -> ConditionItem
	6,  // 8: UserInfos.userinfos:type_name -> UserInfoDB
	9,  // 9: GetUserInfoReq.cond:type_name -> Condition
	10, // 10: GetUserInfoRes.data:type_name -> UserInfos
	9,  // 11: DeleteUserInfoReq.cond:type_name -> Condition
	0,  // 12: CreateUserInfoReq.sex:type_name -> Sex
	4,  // 13: CreateUserInfoReq.card_type:type_name -> CardType
	6,  // 14: CreateUserInfoRes.data:type_name -> UserInfoDB
	9,  // 15: ModifyUserInfoReq.cond:type_name -> Condition
	0,  // 16: ModifyUserInfoReq.sex:type_name -> Sex
	4,  // 17: ModifyUserInfoReq.card_type:type_name -> CardType
	1,  // 18: ModifyUserInfoReq.status:type_name -> UserStatus
	6,  // 19: ModifyUserInfoRes.data:type_name -> UserInfoDB
	6,  // 20: GetUserInfoByIDRes.data:type_name -> UserInfoDB
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_user_msg_proto_init() }
func file_user_msg_proto_init() {
	if File_user_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfoDB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionItemArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Condition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyUserInfoRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_msg_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoByIDRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_msg_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_msg_proto_goTypes,
		DependencyIndexes: file_user_msg_proto_depIdxs,
		EnumInfos:         file_user_msg_proto_enumTypes,
		MessageInfos:      file_user_msg_proto_msgTypes,
	}.Build()
	File_user_msg_proto = out.File
	file_user_msg_proto_rawDesc = nil
	file_user_msg_proto_goTypes = nil
	file_user_msg_proto_depIdxs = nil
}
